### ISSUE TITLE
error in QCD::mp2mbar

### ISSUE THREAD

**Issue by ycwu1030** [silvest/HEPfit#2]
Hi:
  I didn't change anything here, but just run the example in LibMode_config and LibMode_header. These two examples will return the `error in QCD::mp2mbar` with `Error in <ROOT::Math::BrentRootFinder>: Interval does not contain a root`. I'm not expert in QCD, how should I fix this error? Thanks!

Best
ycwu

**Comment by ycwu1030** [comment]
I'm using the HEPfit 1.0 version with ROOT 6.24/06

**Comment by talismanbrandi** [comment]
Hi,

This error usually arises because of an incorrect input in the configuration files. Can you please let us know what configuration files you are using, are they the ones we provided or did you make your own?

**Comment by ycwu1030** [comment]
> 

Hi:
   Sorry for forgetting mentioning the config file. I used the one shipped with HEPfit inside the example/config folder. (StandardModel.conf)

Best

**Comment by ycwu1030** [comment]
Also, for the example in LibMode_header, no config file is needed, I will also get this error. Thanks!

**Comment by silvest** [comment]
Hi @ycwu1030 ,

could you please pull the latest version and try again?

Thanks a lot,
Best Regards,
Luca
